In [1]:
import numpy as np

## numpy array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
# Burada listemizi numpy dizisine(arrayine) çeviriyoruz:
np.array(benimListem)

array([20, 30, 40])

In [5]:
type(np.array(benimListem)) # görüldüğü gibi numpy.ndarray ile numpy dizisi oluştu

numpy.ndarray

In [6]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [7]:
type(matrixListesi)

list

In [8]:
matrixListesi[1]

[20, 30, 40]

In [9]:
matrixListesi[1][0]

20

In [12]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [13]:
# arange : numpy dizisi(arrayi) oluşturur, liste oluşturmaz.
# range ile listeler oluşturabiliyorduk :
list(range(0,10)) # 0 dahil 10 hariç liste oluşturur.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
np.arange(0,10) # 0 dahil 10 hariç numpy dizisi oluşturur.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,100,4) # 4 : stepsize

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

## zeros & ones

In [19]:
np.zeros(5) # İçerisinde 5 tane sıfır olan numpy dizisi oluşturur.

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [27]:
# linspace : Belli değerler arasında eşit aralıklı bir dizi oluşturmak istersek kullanırız.
np.linspace(0,20,6) # 0 ve 20 dahil 6 tane eşit aralıklı dizi oluşturur.

array([ 0.,  4.,  8., 12., 16., 20.])

In [28]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [29]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [31]:
# Burada eye 3'e 3'lük matrix oluşturur. Sadece diagonal yapısı 1'lerden oluşsun, geri kalan tüm sayılar 0 olsun der:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [38]:
# Bize 4 tane rastgele float değerler içeren numpy dizisi döndürür.
# Her çalıştırdığımızda ekrana farklı sonuçlar getirir.
np.random.randn(4) # Kısaca randn float değerler içeren numpy dizisi döndürür.

array([-0.17824474,  0.26001476, -2.06040783,  0.89604573])

In [40]:
np.random.randn(8,8)

array([[-1.25601544,  1.07972945,  0.23758354, -1.00323555, -1.1644401 ,
         1.47547622,  0.15352068,  0.26278634],
       [ 1.28380366, -1.47475323, -0.34566366, -0.60189679,  0.36313411,
        -0.09661789, -0.72302229,  0.7653396 ],
       [-1.85391454, -0.18599422, -1.50612158, -0.56705067, -0.49320892,
         0.65350341, -0.1171233 , -1.37411491],
       [-0.17120125, -1.31032906, -1.26039215, -0.4403813 ,  1.16675952,
        -0.90760364, -0.72022999,  0.53856649],
       [ 0.96196249, -1.41580833,  0.61565901,  0.6715678 ,  0.15351871,
        -0.55185541, -0.09359141, -2.43530806],
       [-1.14620973,  1.22476201,  0.40029482, -0.37153011,  1.23748775,
        -0.92917653, -1.24598904, -2.32382226],
       [ 0.67607003, -1.01174838,  0.76514883,  2.10659793, -0.61663457,
         0.90580583,  0.61552741, -0.37961685],
       [ 0.71124894, -0.37624304, -0.35459274,  0.34630061, -0.28176564,
        -1.64425257, -0.15167708,  0.35039399]])

In [48]:
np.random.randint(0,10) # 0 dahil 10 hariç random integer sayı üretir.

0

In [49]:
np.random.randint(10) # 0 dahil 10 hariç random integer sayı üretir.

4

In [50]:
np.random.randint(1,20,5) # 1 dahil 20 hariç 5 tane random integer sayı dizisi bize döndürür.

array([4, 3, 6, 9, 7])

In [53]:
np.random.randint(1,300,5)

array([252, 255, 122, 201,  63])

In [54]:
benimNumpyDizim = np.arange(30)

In [55]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [66]:
benimRandomDizim = np.random.randint(0,100,20)

In [67]:
benimRandomDizim

array([39, 34, 41,  8, 55, 84, 56, 90, 47, 33, 48, 14,  4, 81, 21, 69, 12,
       39, 97, 68])

## numpy dizi metodları

In [68]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [69]:
benimRandomDizim.max()

97

In [70]:
benimRandomDizim.min()

4

In [71]:
benimRandomDizim.argmax() # argmax() ile maximum olan sayının kaçıncı indexte olduğunu öğreniriz.

18

In [72]:
benimRandomDizim.argmin()

12

In [74]:
benimNumpyDizim.shape # shape() parantez yoktur. Çünkü bu metod veya fonksiyon değil bildiğimiz bir özellik(attribute.)

(30,)

In [75]:
benimRandomDizim.shape

(20,)

In [76]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [77]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [78]:
reshapeDizim.shape

(5, 6)