In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimDizim[3:8] = -5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [11]:
baskaDizi = np.arange(0,24)

In [12]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
slicingDizisi = baskaDizi[4:9]

In [20]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [21]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
type(slicingDizisi)

numpy.ndarray

In [23]:
slicingDizisi[:]

array([4, 5, 6, 7, 8])

In [24]:
slicingDizisi[:] = 700

In [25]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [26]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [27]:
ornekDizi = np.arange(0,24)

In [28]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [29]:
# Şimdi ornekDizi'nin kopyasını oluşturup aşağıda yapılan işlemler ornekDiziyi etkilemesin istiyoruz:
ornekDiziKopyasi = ornekDizi.copy()

In [30]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [33]:
ornekDiziKopyaSlicing

array([3, 4, 5])

In [34]:
ornekDiziKopyaSlicing[:] = 800

In [35]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [36]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [37]:
ornekDizi # orijinal dizide değişiklik yok.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [38]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [39]:
type(benimListem)

list

In [40]:
benimMatrixDizim = np.array(benimListem)

In [41]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [42]:
type(benimMatrixDizim)

numpy.ndarray

In [43]:
benimMatrixDizim[0]

array([10, 20, 30])

In [44]:
benimMatrixDizim[0][2]

30

In [45]:
benimMatrixDizim[0,2] # ilk önce row'da 0. row'u al, sonra columnda 2. index'i al.

30

In [46]:
benimMatrixDizim[1:,2] # 1. rowdan itibaren 2. indexdeki sayıları al.
# 1. row ve 2. rowu getir , daha sonra onların sadece 2. indexdeki sayılarını al.

array([40, 60])

In [47]:
benimMatrixDizim[2:,1] # 2. rowdan itibaren sadece 1. indexdeki sayıyı al.
# 2. rowu getir , daha sonra sadece 1. indexdeki sayıyı al.

array([50])

In [48]:
benimMatrixDizim[2:,1:] # 2. rowdan itibaren ve 1. indexden(columndaki) itibaren olan sayıları al.
# 2. row 1. columdan itibaren tüm sayıları al.

array([[50, 60]])

In [49]:
benimMatrixDizim[0:,2] 

array([30, 40, 60])

In [50]:
benimMatrixDizim[2:,0] 

array([40])

In [51]:
benimMatrixDizim[2:,0:]

array([[40, 50, 60]])

In [52]:
benimMatrixDizim[2:,2:]

array([[60]])

In [54]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [55]:
yeniMatrix = np.array(yeniListe)

In [56]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [60]:
yeniMatrix[[4,2,0]] # 4,2 ve 0. indexler bize gelir. Burada index yerine [4,2,0] diye bir liste verilir. O listedeki indexlere göre ayrı bir dizi oluşturup karşımıza getirir. 

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [69]:
yeniBirDizi = np.random.randint(1,100,20)

In [70]:
yeniBirDizi

array([10, 88, 39, 82, 20, 74, 22, 95, 10, 46, 66, 49, 49, 18, 37,  9, 14,
       14, 40, 12])

In [72]:
# yeniBirDizi içerisinde 24'dan büyük sayıları bul :
yeniBirDizi > 24

array([False,  True,  True,  True, False,  True, False,  True, False,
        True,  True,  True,  True, False,  True, False, False, False,
        True, False])

In [73]:
yeniBirDizi

array([10, 88, 39, 82, 20, 74, 22, 95, 10, 46, 66, 49, 49, 18, 37,  9, 14,
       14, 40, 12])

In [74]:
sonucDizisi = yeniBirDizi > 24

In [75]:
sonucDizisi

array([False,  True,  True,  True, False,  True, False,  True, False,
        True,  True,  True,  True, False,  True, False, False, False,
        True, False])

In [76]:
yeniBirDizi

array([10, 88, 39, 82, 20, 74, 22, 95, 10, 46, 66, 49, 49, 18, 37,  9, 14,
       14, 40, 12])

In [77]:
# Sadece 24'den büyük olan sayıları filtreleyip ekrana getirir. False, true arasından sadece true olanları ekrana getirir.
yeniBirDizi[sonucDizisi] # Bu bize yeniBirDizi içinde 24'den büyük olan sayı dizisini ekrana getirir.

array([88, 39, 82, 74, 95, 46, 66, 49, 49, 37, 40])

In [79]:
yeniBirDizi[yeniBirDizi>24] # Bir diziyi filtrelemek istersek kullanırız.

array([88, 39, 82, 74, 95, 46, 66, 49, 49, 37, 40])

In [80]:
sonDizi = np.arange(0,24)

In [81]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [82]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [83]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [84]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [85]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [86]:
sonDizi / sonDizi

C:\Users\elifn_hb9g\AppData\Local\Temp\ipykernel_7648\1312094733.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [87]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [88]:
np.max(sonDizi)

23

In [89]:
np.min(sonDizi)

0